name: Retail Churn Prediction CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.8"

            - name: Install dependencies
              run: |
                  pip install -r requirements.txt

            - name: Run tests
              run: |
                  pytest

            - name: Build Docker image
              run: |
                  docker build -t retail-churn .

            - name: Push Docker image
              run: |
                  docker tag retail-churn registry.example.com/retail-churn:v1
                  docker push registry.example.com/retail-churn:v1

    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to production
              run: |
                  ssh user@yourserver "docker pull registry.example.com/retail-churn:v1 && docker-compose up -d"
